### ISSUE TITLE
Can you help me：url: https://huggingface.co/sd_model_v1-5/resolve/main/unet/config.json

### ISSUE THREAD

**Issue by yangfanooo** [Xiaojiu-z/Stable-Makeup#11]
(.venv) D:\Stable-Makeup-main>d:/Stable-Makeup-main/.venv/Scripts/python.exe d:/Stable-Makeup-main/infer_kps.py
d:\Stable-Makeup-main\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
SPIGA model loaded!
SPIGA model loaded!
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to 
force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/sd_model_v1-5/resolve/main/unet/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Stable-Makeup-main\diffusers\configuration_utils.py", line 370, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 1823, in _raise_on_head_call_error
    raise head_call_error
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 396, in _request_wrapper
    hf_raise_for_status(response)
  File "d:\Stable-Makeup-main\.venv\Lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-668e4001-33d97afb05bb91ed5fd81209;fc9fca5a-311b-4964-a2a9-10720043ce83)

Repository Not Found for url: https://huggingface.co/sd_model_v1-5/resolve/main/unet/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Stable-Makeup-main\infer_kps.py", line 47, in <module>
    Unet = OriginalUNet2DConditionModel.from_pretrained(model_id, subfolder="unet").to("cuda")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\diffusers\models\modeling_utils.py", line 704, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "d:\Stable-Makeup-main\diffusers\configuration_utils.py", line 384, in load_config
    raise EnvironmentError(
OSError: sd_model_v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.

**Comment by Xiaojiu-z** [comment]
> sd_model_v1-5

You need to change "sd_model_v1-5" into your local path or huggingface path.
