### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by zachysaur** [Xiaojiu-z/Stable-Makeup#23]
(venv) F:\stable makeup\New folder\Stable-Makeup-main>python d:/Stable-Makeup-main/infer_kps.py --id_input path/to/image.png --makeup_reference path/to/makeup_image.png --output_dir ./output
C:\Users\ggrov\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'd:\\Stable-Makeup-main\\infer_kps.py': [Errno 2] No such file or directory

(venv) F:\stable makeup\New folder\Stable-Makeup-main>python inference.py --id_input ./test_imgs/id/1.jpg --makeup_reference ./test_imgs/makeup/1.jpg --output_dir ./output
SPIGA model loaded!
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.1+cu121 with CUDA 1201 (you have 2.2.1+cu118)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
F:\stable makeup\New folder\Stable-Makeup-main\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\stable makeup\New folder\Stable-Makeup-main\diffusers\configuration_utils.py", line 370, in load_config
    config_file = hf_hub_download(
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 1854, in _raise_on_head_call_error
    raise head_call_error
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "F:\stable makeup\New folder\Stable-Makeup-main\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66e084ab-4f82ff6966c453b11dcb2efd;2c86837b-264c-47ba-97c4-42674ff0b171)

Repository Not Found for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable makeup\New folder\Stable-Makeup-main\inference.py", line 8, in <module>
    from inference_utils import inference
  File "F:\stable makeup\New folder\Stable-Makeup-main\inference_utils.py", line 87, in <module>
    pipeline, makeup_encoder = init_pipeline()
  File "F:\stable makeup\New folder\Stable-Makeup-main\inference_utils.py", line 65, in init_pipeline
    Unet              = OriginalUNet2DConditionModel.from_pretrained(model_id, subfolder="unet").to("cuda")
  File "F:\stable makeup\New folder\Stable-Makeup-main\diffusers\models\modeling_utils.py", line 704, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "F:\stable makeup\New folder\Stable-Makeup-main\diffusers\configuration_utils.py", line 384, in load_config
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.

(venv) F:\stable makeup\New folder\Stable-Makeup-main>

**Comment by kr150** [comment]
看起来这像是runway删库导致找不到权重，hugging face上找个新的仓库即可
