### ISSUE TITLE
image_encoder_l

### ISSUE THREAD

**Issue by kigy1** [Xiaojiu-z/Stable-Makeup#5]
thanks for your work, i try the gradio_demo_kps.py
but it show me models/image_encoder_l' , not found where i can get this files ?

C:\Users\GAMER\Desktop\Stable-Makeup-main>gradio_demo_kps.py
C:\Users\GAMER\Desktop\Stable-Makeup-main\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
SPIGA model loaded!
SPIGA model loaded!
C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './models/image_encoder_l'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GAMER\Desktop\Stable-Makeup-main\gradio_demo_kps.py", line 42, in <module>
    makeup_encoder = detail_encoder(Unet, "./models/image_encoder_l", "cuda", dtype=torch.float32)
  File "C:\Users\GAMER\Desktop\Stable-Makeup-main\detail_encoder\encoder_plus.py", line 28, in __init__
    clip_encoder = OriginalCLIPVisionModel.from_pretrained(image_encoder_path)
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 3015, in from_pretrained
    resolved_config_file = cached_file(
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: './models/image_encoder_l'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by Xiaojiu-z** [comment]
> thanks for your work, i try the gradio_demo_kps.py but it show me models/image_encoder_l' , not found where i can get this files ?
> 
> C:\Users\GAMER\Desktop\Stable-Makeup-main>gradio_demo_kps.py C:\Users\GAMER\Desktop\Stable-Makeup-main\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. torch.utils._pytree._register_pytree_node( SPIGA model loaded! SPIGA model loaded! C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`. warnings.warn( Traceback (most recent call last): File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py", line 398, in cached_file resolved_file = hf_hub_download( File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils_validators.py", line 106, in _inner_fn validate_repo_id(arg_value) File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils_validators.py", line 154, in validate_repo_id raise HFValidationError( huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './models/image_encoder_l'. Use `repo_type` argument if needed.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\GAMER\Desktop\Stable-Makeup-main\gradio_demo_kps.py", line 42, in makeup_encoder = detail_encoder(Unet, "./models/image_encoder_l", "cuda", dtype=torch.float32) File "C:\Users\GAMER\Desktop\Stable-Makeup-main\detail_encoder\encoder_plus.py", line 28, in **init** clip_encoder = OriginalCLIPVisionModel.from_pretrained(image_encoder_path) File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 3015, in from_pretrained resolved_config_file = cached_file( File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py", line 462, in cached_file raise EnvironmentError( OSError: Incorrect path_or_model_id: './models/image_encoder_l'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

Oh, the solution to this problem is to download openai/clip-vit-large-patch14 from hugging face, save it locally, and load it.

**Comment by kigy1** [comment]
great that fix, but..........it's take time and no things happened, i'm sorry if this annoying you and thanks again

![Screenshot 2024-05-06 003836](https://github.com/Xiaojiu-z/Stable-Makeup/assets/136764953/2b8f01a7-d27f-46bd-a5cd-34f4d1e85bbe)


SPIGA model loaded!
SPIGA model loaded!
C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...:  17%|████████▋                                           | 1/6 [00:00<00:00,  5.17it/s]C:\Users\GAMER\Desktop\Stable-Makeup-main\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:00<00:00, 23.26it/s]
You have disabled the safety checker for <class 'pipeline_sd15.StableDiffusionControlNetPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:257: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:89: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\outputs.py:43: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='946gtlhd73s_0' coro=<Queue.process_events() done, defined at C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': '946gtlhd73s'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing>
Traceback (most recent call last):
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': '946gtlhd73s'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by Xiaojiu-z** [comment]
> great that fix, but..........it's take time and no things happened, i'm sorry if this annoying you and thanks again
> 
> ![Screenshot 2024-05-06 003836](https://private-user-images.githubusercontent.com/136764953/328051819-2b8f01a7-d27f-46bd-a5cd-34f4d1e85bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODc5NDIsIm5iZiI6MTcxNDk4NzY0MiwicGF0aCI6Ii8xMzY3NjQ5NTMvMzI4MDUxODE5LTJiOGYwMWE3LWQyN2YtNDZiZC1hNWNkLTM0ZjRkMWU4NWJiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwOTI3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZThkMjdiYzBiYjljNDVkNDlkZWUwZWUzNGY1MjU2NWNjNzUxZDAxYTM0ZjgxZGMyMjgxN2Y0YzBiOWI0NzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2EsP1aFQQ8NiaPCfwkBJKG3Nio26BhxEQf20uAb24k8)
> 
> SPIGA model loaded! SPIGA model loaded! C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`. warnings.warn( Loading pipeline components...: 17%|████████▋ | 1/6 [00:00<00:00, 5.17it/s]C:\Users\GAMER\Desktop\Stable-Makeup-main\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. torch.utils._pytree._register_pytree_node( Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:00<00:00, 23.26it/s] You have disabled the safety checker for <class 'pipeline_sd15.StableDiffusionControlNetPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at [huggingface/diffusers#254](https://github.com/huggingface/diffusers/pull/254) . C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:257: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components warnings.warn( C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect warnings.warn(value) C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:89: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components warnings.warn( C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\outputs.py:43: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components warnings.warn( Running on local URL: http://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`. Task exception was never retrieved future: <Task finished name='946gtlhd73s_0' coro=<Queue.process_events() done, defined at C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody event_id Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': '946gtlhd73s'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing> Traceback (most recent call last): File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 347, in process_events client_awake = await self.gather_event_data(event) File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data data, client_awake = await self.get_message(event, timeout=receive_timeout) File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 456, in get_message return PredictBody(**data), True File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 176, in **init** self.**pydantic_validator**.validate_python(data, self_instance=self) pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody event_id Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': '946gtlhd73s'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing

Maybe try again or change the version of gr I have never encountered this problem before. I hope this helps.

**Comment by kigy1** [comment]
thanks, work will now, like what you said the problem is from new version of gradio so i edit the code to work with the new version

the edit is for
gradio_demo_kps.py

replace it with this
# Create a Gradio interface
image1 = gr.Image(label="id_image")
image2 = gr.Image(label="makeup_image")
number = gr.Slider(minimum=1.01, maximum=5, value=1.5, label="makeup_guidance_scale")
output = gr.Image(type="pil", label="Output Image")


i remove inputs and output also change default=1.5 to value=1.5


great work, best wishes..........

**Comment by kigy1** [comment]
this for everyone Maybe it will help those who have problems

It took time for me, but it works now. 

I created a new environment, but I don't think it was necessary. 

need the following libraries: 
• PyTorch (I have version 2.3.0+cu118; you can get it from the PyTorch website)
• Gradio
• Safetensors
• Transformers
• Datasets
• Spiga (after installation, you need to put spiga_300wpublic.pt in spiga/models/weights/)
• Facelib (you can get it from GitHub)
• Accelerate 

Also, you need to download openai/clip-vit-large-patch14 and put it in Stable-Makeup-main\models\image_encoder_l. You only need config.json and pytorch_model.bin. also, you need the main models for Stable-Makeup, and put it in models\stablemakeup. 

Finally, you need to make some changes to the code in gradio_demo_kps.py 

# Initialize the model
model_id = "runwayml/stable-diffusion-v1-5"  # your sd1.5 model path 

# Create a Gradio interface
image1 = gr.Image(label="id_image")
image2 = gr.Image(label="makeup_image")
number = gr.Slider(minimum=1.01, maximum=5, value=1.5, label="makeup_guidance_scale")
output = gr.Image(type="pil", label="Output Image")

**Comment by Xiaojiu-z** [comment]
I will reopen this issue so that more people can see it 🎉🎉🎉

**Comment by zachysaur** [comment]
how exactly you installed this?

**Comment by kigy1** [comment]
> how exactly you installed this?

If you allow me @Xiaojiu-z 

@zachysaur this extension will work in automatc1111 and it will be easy
https://github.com/kigy1/sd-webui-Stable-Makeup
